
interface RegionInfo {
  state: string;
  region: string;
  phrase: string;
}

export const dddMap: Record<string, RegionInfo> = {
  "11": { state: "São Paulo (capital)", region: "Sudeste", phrase: "da terra da garoa e do progresso" },
  "12": { state: "São Paulo", region: "Sudeste", phrase: "do Vale do Paraíba" },
  "13": { state: "São Paulo", region: "Sudeste", phrase: "da Baixada Santista" },
  "14": { state: "São Paulo", region: "Sudeste", phrase: "de Bauru e região" },
  "15": { state: "São Paulo", region: "Sudeste", phrase: "de Sorocaba e região" },
  "16": { state: "São Paulo", region: "Sudeste", phrase: "de Ribeirão Preto" },
  "17": { state: "São Paulo", region: "Sudeste", phrase: "de São José do Rio Preto" },
  "18": { state: "São Paulo", region: "Sudeste", phrase: "do oeste paulista" },
  "19": { state: "São Paulo", region: "Sudeste", phrase: "de Campinas e região" },
  "21": { state: "Rio de Janeiro", region: "Sudeste", phrase: "da Cidade Maravilhosa" },
  "22": { state: "Rio de Janeiro", region: "Sudeste", phrase: "do Norte Fluminense" },
  "24": { state: "Rio de Janeiro", region: "Sudeste", phrase: "da Região Serrana" },
  "27": { state: "Espírito Santo", region: "Sudeste", phrase: "de Vitória e região" },
  "28": { state: "Espírito Santo", region: "Sudeste", phrase: "do sul capixaba" },
  "31": { state: "Minas Gerais", region: "Sudeste", phrase: "da terra do pão de queijo" },
  "32": { state: "Minas Gerais", region: "Sudeste", phrase: "da Zona da Mata mineira" },
  "33": { state: "Minas Gerais", region: "Sudeste", phrase: "do Jequitinhonha" },
  "34": { state: "Minas Gerais", region: "Sudeste", phrase: "do Triângulo Mineiro" },
  "35": { state: "Minas Gerais", region: "Sudeste", phrase: "do Sul de Minas" },
  "37": { state: "Minas Gerais", region: "Sudeste", phrase: "do Centro-Oeste mineiro" },
  "38": { state: "Minas Gerais", region: "Sudeste", phrase: "do Norte de Minas" },
  "41": { state: "Paraná", region: "Sul", phrase: "da terra dos pinheirais" },
  "42": { state: "Paraná", region: "Sul", phrase: "dos Campos Gerais" },
  "43": { state: "Paraná", region: "Sul", phrase: "do Norte do Paraná" },
  "44": { state: "Paraná", region: "Sul", phrase: "do Noroeste Paranaense" },
  "45": { state: "Paraná", region: "Sul", phrase: "do Oeste Paranaense" },
  "46": { state: "Paraná", region: "Sul", phrase: "do Sudoeste Paranaense" },
  "47": { state: "Santa Catarina", region: "Sul", phrase: "do Vale do Itajaí" },
  "48": { state: "Santa Catarina", region: "Sul", phrase: "da Grande Florianópolis" },
  "49": { state: "Santa Catarina", region: "Sul", phrase: "do Oeste Catarinense" },
  "51": { state: "Rio Grande do Sul", region: "Sul", phrase: "da terra do chimarrão" },
  "53": { state: "Rio Grande do Sul", region: "Sul", phrase: "da região Sul gaúcha" },
  "54": { state: "Rio Grande do Sul", region: "Sul", phrase: "da Serra Gaúcha" },
  "55": { state: "Rio Grande do Sul", region: "Sul", phrase: "da Fronteira Oeste" },
  "61": { state: "Distrito Federal", region: "Centro-Oeste", phrase: "da capital do país" },
  "62": { state: "Goiás", region: "Centro-Oeste", phrase: "terra do pequi" },
  "63": { state: "Tocantins", region: "Norte", phrase: "do mais novo estado brasileiro" },
  "64": { state: "Goiás", region: "Centro-Oeste", phrase: "do Sul Goiano" },
  "65": { state: "Mato Grosso", region: "Centro-Oeste", phrase: "do Portal da Amazônia" },
  "66": { state: "Mato Grosso", region: "Centro-Oeste", phrase: "da região do Araguaia" },
  "67": { state: "Mato Grosso do Sul", region: "Centro-Oeste", phrase: "terra do Pantanal" },
  "68": { state: "Acre", region: "Norte", phrase: "da terra dos dinossauros" },
  "69": { state: "Rondônia", region: "Norte", phrase: "terra da castanha" },
  "71": { state: "Bahia", region: "Nordeste", phrase: "da terra do axé" },
  "73": { state: "Bahia", region: "Nordeste", phrase: "da Costa do Cacau" },
  "74": { state: "Bahia", region: "Nordeste", phrase: "do sertão baiano" },
  "75": { state: "Bahia", region: "Nordeste", phrase: "do Recôncavo Baiano" },
  "77": { state: "Bahia", region: "Nordeste", phrase: "do Oeste Baiano" },
  "79": { state: "Sergipe", region: "Nordeste", phrase: "do menor estado brasileiro" },
  "81": { state: "Pernambuco", region: "Nordeste", phrase: "da terra do frevo" },
  "82": { state: "Alagoas", region: "Nordeste", phrase: "terra dos lindos mares" },
  "83": { state: "Paraíba", region: "Nordeste", phrase: "terra do sol nascente" },
  "84": { state: "Rio Grande do Norte", region: "Nordeste", phrase: "terra do sol e do mar" },
  "85": { state: "Ceará", region: "Nordeste", phrase: "da terra da luz" },
  "86": { state: "Piauí", region: "Nordeste", phrase: "do Delta do Parnaíba" },
  "87": { state: "Pernambuco", region: "Nordeste", phrase: "do sertão pernambucano" },
  "88": { state: "Ceará", region: "Nordeste", phrase: "do interior cearense" },
  "89": { state: "Piauí", region: "Nordeste", phrase: "do sertão piauiense" },
  "91": { state: "Pará", region: "Norte", phrase: "da terra do açaí" },
  "92": { state: "Amazonas", region: "Norte", phrase: "da terra das águas" },
  "93": { state: "Pará", region: "Norte", phrase: "da região de Santarém" },
  "94": { state: "Pará", region: "Norte", phrase: "da região de Marabá" },
  "95": { state: "Roraima", region: "Norte", phrase: "do extremo norte do Brasil" },
  "96": { state: "Amapá", region: "Norte", phrase: "da terra do meio do mundo" },
  "97": { state: "Amazonas", region: "Norte", phrase: "do interior amazonense" },
  "98": { state: "Maranhão", region: "Nordeste", phrase: "dos lençóis maravilhosos" },
  "99": { state: "Maranhão", region: "Nordeste", phrase: "do sertão maranhense" },
};

export function getRegionInfo(ddd: string): RegionInfo | null {
  return dddMap[ddd] || null;
}
